cmake_minimum_required(VERSION 3.20)
include("${CMAKE_CURRENT_LIST_DIR}/../../cmake/version.cmake")

if(DEFINED MANIFEST)
  worm_read_version("${MANIFEST}")
  return()
endif()

file(MAKE_DIRECTORY "${TEST_ROOT}")
function(check_version version request expected)
  set(fixture "${TEST_ROOT}/${version}")
  file(MAKE_DIRECTORY "${fixture}")
  file(WRITE "${fixture}/vcpkg.json" "{\"version-semver\":\"${version}\"}")
  worm_read_version("${fixture}/vcpkg.json")
  worm_write_package_version("${fixture}/WormConfigVersion.cmake")
  file(WRITE "${fixture}/WormConfig.cmake" "set(Worm_VERSION \"${WORM_VERSION}\")\n")
  string(MD5 caseId "${version}|${request}")
  execute_process(COMMAND "${CMAKE_COMMAND}"
    -S "${CMAKE_CURRENT_LIST_DIR}/version-consumer" -B "${TEST_ROOT}/consumer-${caseId}"
    "-DPACKAGE_DIR=${fixture}" "-DREQUEST=${request}" "-DEXPECT_FOUND=${expected}" "-DEXPECT_VERSION=${version}"
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
  if(NOT result STREQUAL "0")
    message(FATAL_ERROR "Version case ${version} / '${request}': ${output}\n${error}")
  endif()
endfunction()

check_version(0.1.0 "" TRUE)
check_version(0.1.0 "0.1.0" TRUE)
check_version(0.1.0 "0.1.0;EXACT" TRUE)
check_version(0.1.0 "0.0.9" FALSE)
check_version(0.1.0 "0.1.1" FALSE)
check_version(0.1.0 "0.1.0.1" FALSE)
check_version(0.1.0 "0.1.0...0.2.0" FALSE)
check_version(1.2.3 "1.0" TRUE)
check_version(1.2.3 "1.2.3;EXACT" TRUE)
check_version(1.2.3 "1.2.2;EXACT" FALSE)
check_version(1.2.3 "1.2.4" FALSE)
check_version(1.2.3 "0.9" FALSE)
check_version(1.2.3 "2.0" FALSE)
check_version(1.2.3 "1.0...<2.0" TRUE)
check_version(1.2.3 "1.0...<1.2.3" FALSE)
check_version(1.2.3 "1.0...1.2.3" TRUE)
foreach(stage alpha beta rc)
  check_version(1.0.0-${stage}.1 "" TRUE)
  check_version(1.0.0-${stage}.1 "1.0.0" FALSE)
  check_version(1.0.0-${stage}.1 "1.0.0;EXACT" FALSE)
  check_version(1.0.0-${stage}.1 "1.0...<2.0" FALSE)
endforeach()

foreach(invalid "1.0" "01.0.0" "1.01.0" "1.0.01" "1.0.0-rc.01" "1.0.0-dev.1" "1.0.0+build.1" "v1.0.0")
  file(WRITE "${TEST_ROOT}/invalid.json" "{\"version-semver\":\"${invalid}\"}")
  execute_process(COMMAND "${CMAKE_COMMAND}" "-DMANIFEST=${TEST_ROOT}/invalid.json" -P "${CMAKE_CURRENT_LIST_FILE}"
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
  if(result STREQUAL "0" OR NOT error MATCHES "Invalid Worm release version")
    message(FATAL_ERROR "Expected invalid-version rejection for '${invalid}': ${output}\n${error}")
  endif()
endforeach()

# Run the release checker against a disposable source/artifact pair, including prereleases.
set(releaseRoot "${TEST_ROOT}/release")
file(MAKE_DIRECTORY "${releaseRoot}/cmake")
file(COPY "${CMAKE_CURRENT_LIST_DIR}/../../cmake/version.cmake"
  "${CMAKE_CURRENT_LIST_DIR}/../../cmake/check-release-version.cmake" DESTINATION "${releaseRoot}/cmake")
foreach(version "0.1.0" "1.0.0" "1.0.0-alpha.1" "1.0.0-beta.2" "1.0.0-rc.3")
  file(WRITE "${releaseRoot}/vcpkg.json" "{\"version-semver\":\"${version}\"}")
  foreach(scenario valid wrong-tag wrong-artifact)
    set(tag "v${version}")
    set(artifact "${version}")
    if(scenario STREQUAL "wrong-tag")
      set(tag "v9.0.0")
    elseif(scenario STREQUAL "wrong-artifact")
      set(artifact "9.0.0")
    endif()
    file(WRITE "${releaseRoot}/WormVersion.txt" "${artifact}\n")
    execute_process(COMMAND "${CMAKE_COMMAND}" "-DWORM_RELEASE_TAG=${tag}"
      "-DWORM_ARTIFACT_VERSION_FILE=${releaseRoot}/WormVersion.txt" -P "${releaseRoot}/cmake/check-release-version.cmake"
      RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(scenario STREQUAL "valid")
      if(NOT result STREQUAL "0")
        message(FATAL_ERROR "Valid release rejected: ${output}\n${error}")
      endif()
    elseif(result STREQUAL "0" OR NOT error MATCHES "Release tag must be|Artifact version")
      message(FATAL_ERROR "Expected ${scenario} rejection: ${output}\n${error}")
    endif()
  endforeach()
endforeach()

worm_read_version("${releaseRoot}/vcpkg.json")
execute_process(COMMAND "${CMAKE_COMMAND}" "-DWORM_RELEASE_TAG=v${WORM_VERSION}"
  "-DWORM_CLI_EXECUTABLE=${CMAKE_COMMAND}" -P "${releaseRoot}/cmake/check-release-version.cmake"
  RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(result STREQUAL "0" OR NOT error MATCHES "CLI version mismatch")
  message(FATAL_ERROR "Expected CLI version rejection: ${output}\n${error}")
endif()
